project_id = "hwzssuideymfwjeivwlg"

[auth]
enabled = true

[functions.chat]
verify_jwt = false

[functions.edit-image]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false